dofile(minetest.get_modpath("hades_endgame").."/items.lua")
dofile(minetest.get_modpath("hades_endgame").."/nodes.lua")
dofile(minetest.get_modpath("hades_endgame").."/tools.lua")
dofile(minetest.get_modpath("hades_endgame").."/moist.lua")
dofile(minetest.get_modpath("hades_endgame").."/mapgen.lua")